# You must change these to your own details.
[package]
name = "parser"
description = "Inp parser for wasm"
version = "0.1.0"
authors = ["xuaps <admin@xuaps.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

